### ISSUE TITLE
Allow QIDs as resources

### ISSUE THREAD

**Issue by ProgVal** [ProjetPP/PPP-Wikidata#104]
`(?, [occupation, position held], Q11696)` gets no responses

http://askplatyp.us/?lang=en&q=%28%3F%2C+%5Boccupation%2C+position+held%5D%2C+Q11696%29

**Comment by Ezibenroc** [comment]
:+1:

Then the user would be able to ask `Who is the P26 of the P35 of the Q30?`

I am sure Wikidata community will love this!

**Comment by Tpt** [comment]
Good idea! And it's easy to implement.

**Comment by Ezibenroc** [comment]
In fact, not sure it is a good idea to allow it in natural language questions.

If some user is searching information about the [gene p35](https://en.wikipedia.org/wiki/P35_(gene)) or the [TV station Q30](https://en.wikipedia.org/wiki/Q30), he/she will be very surprised to have as answer `head of government` or `United States of America`.

Maybe keep it for the power user input (but it might be less easy to code).

**Comment by Tpt** [comment]
>Maybe keep it for the power user input (but it might be less easy to code).
The big issue is that it's difficult to know that the question is from the power user input.

I think that the number of real things that are called QXX and properties that are called PYY is low enough to make this not a real problem (there are far more important bugs to fix and features to implement).
