### ISSUE TITLE
Does not seem to requests in French anymore

### ISSUE THREAD

**Issue by ProgVal** [ProjetPP/PPP-Wikidata#91]
From the CLI:

```
progval@ganymede:~/etudes/ens/ppp/integration(master)$ python3 -m ppp_cli --lang fr "Quelle est la date de naissance d’Obama ?"

Response (PLYFrenchParser):
    Subject: Obama
    Predicate: date de naissance
    Object: ?
```

On Travis: https://travis-ci.org/ProjetPP/integration/builds/50730019#L1657

**Comment by Tpt** [comment]
It is just because there is no alias "Obama" in French in the item about Barack Obama in the currently used dump http://askplatyp.us/?lang=fr&q=%28Barack+Obama%2C+date+de+naissance%2C+%3F%29

**Comment by ProgVal** [comment]
What about Travis?

**Comment by Tpt** [comment]
Good question. I don't know how the Wikidata module with the API storage can fail on it (language coverage with the API backend is well tested in https://github.com/ProjetPP/PPP-Wikidata/blob/master/tests/phpunit/WikidataRequestHandlerTest.php ). I've restarted the build.

May it be an error elsewhere in the PPP infrastructure?

**Comment by ProgVal** [comment]
Hmm, actually it looks like the FrenchParser does not do its work on Travis
