### ISSUE TITLE
Use Wikidata formatters?

### ISSUE THREAD

**Issue by ProgVal** [ProjetPP/PPP-Wikidata#98]
It may be nice to use Wikidata formatters for some values, for instance the Freebase identifier.

http://askplatyp.us/?lang=en&q=What+is+the+freebase+identifier+of+Knuth%3F

**Comment by Tpt** [comment]
> for instance the Freebase identifier.

It's not possible to reuse Wikibase formatters for this use case as the creation of links for such identifiers is currently done by a JavaScript gadget. So we will have to write some PHP code for it.

> It may be nice to use Wikidata formatters for some values.

It is already done for "value" parameter of resources.
